In [140]:
import pandas as pd

# To display all rows
pd.set_option('display.max_rows', None) 

# To display all columns
pd.set_option('display.max_columns', None)

# Q1
pd.__version__

'2.3.1'

In [141]:
# Q2
pd.read_csv("/workspaces/mlzoomcamp2025/laptops.csv")

# There are 2160 'records' but only 2159 rows of data in the laptops.csv dataset

df = pd.read_csv("/workspaces/mlzoomcamp2025/laptops.csv")

print(df.shape)
df.head()


(2160, 12)


Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

In [142]:
# Q3 - Number of Laptop Brands?

q3ans = df['Brand'].nunique()



print('The number of unique Brands is', q3ans)  


The number of unique Brands is 27


In [143]:
# Q4 - How many columns in dataset have missing values?

q4ans = (df.isnull().sum() > 0).sum()

print('The number of columsn with missing values is', q4ans)  

The number of columsn with missing values is 3


In [144]:
# Q5 - Max Price of Dell Notebooks 

    # max_finalPrice = df['Final Price'].max()
    # print(max_finalPrice)

max_finalPrice_dell = df[df['Brand'] == 'Dell']['Final Price'].max()

print('The max value in Final Price is $',max_finalPrice_dell)  

The max value in Final Price is $ 3936.0


In [145]:
# Q6. Median value of Screen
# Find the median value of Screen column in the dataset.
median_screen = df['Screen'].median() 
print("The MEAN value of 'Screen' column is",median_screen)


# Next, calculate the most frequent value of the same Screen column.
mode_screen = df['Screen'].mode()[0] 
#the mode [0] is to access the first element (and ignore the returned index of the Series)

print("The MODE is", mode_screen) 

print( df.isnull().sum() ) 


The MEAN value of 'Screen' column is 15.6
The MODE is 15.6
Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64


In [146]:
# Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step.
df['Screen'] = df['Screen'].fillna(15.6)

print( df.isnull().sum() )  #confirm 0 empty in ['Screen']

new_mode_screen = df['Screen'].mode()[0] 
print("The MODE is", new_mode_screen) 

# Now, calculate the median value of Screen once again.

new_median_screen = df['Screen'].median() 
print("The MEAN value of 'Screen' column is", new_median_screen)

# Has it changed?
    # No the median value is still 15.6. 

# Hint: refer to existing mode and median functions to complete the task.


Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             0
Touch              0
Final Price        0
dtype: int64
The MODE is 15.6
The MEAN value of 'Screen' column is 15.6


In [147]:
# Q7. Sum of weights

import numpy as np

# Select all the "Innjoo" (its a selection of column 'Brand' ) laptops from the dataset.
# Select only columns RAM, Storage, Screen.
df_injoo = df[df['Brand']=='Innjoo'][['RAM','Storage','Screen']]

# Get the underlying NumPy array. Let's call it X.
x = df_injoo.to_numpy()
print(df_injoo.head(999), "\n") #just to get all rows


print(x, "\n")

# Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

xtx = np.dot(x.T, x)
print(xtx, "\n")

# Compute the inverse of XTX.
xtx_inverse = np.linalg.inv(xtx)
print(xtx_inverse)


      RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1 

[[  8.  256.   15.6]
 [  8.  512.   15.6]
 [  4.   64.   14.1]
 [  6.   64.   14.1]
 [  6.  128.   14.1]
 [  6.  128.   14.1]] 

[[2.52000e+02 8.32000e+03 5.59800e+02]
 [8.32000e+03 3.68640e+05 1.73952e+04]
 [5.59800e+02 1.73952e+04 1.28196e+03]] 

[[ 2.78025381e-01 -1.51791334e-03 -1.00809855e-01]
 [-1.51791334e-03  1.58286725e-05  4.48052175e-04]
 [-1.00809855e-01  4.48052175e-04  3.87214888e-02]]


In [154]:
# Create an array y with values [1100, 1300, 800, 900, 1000, 1100].
y = np.array([1100, 1300, 800, 900, 1000, 1100])

# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
w = xtx_inverse.dot(x.T).dot(y)

print('w is equal to:', w)

# What's the sum of all the elements of the result?
print('The sum of w is',sum(w).round(1) ) 

# Note: You just implemented linear regression. We'll talk about it in the next lesson.

# 0.43
# 45.29
# 45.58
# 91.30

w is equal to: [45.58076606  0.42783519 45.29127938]
The sum of w is 91.3
